### PR TITLE
Finalize Security.md

### PR DESCRIPTION
**Pull request by finnaminope**

### CODE REVIEW

**Comment by HydraDragonAntivirus** [comment]
Your code is broken actually.

**Comment by finnaminope** [comment]
Sorry I forgot about this commit and the code is probably a mess. I'm closing this commit. I'm really sorry for not checking my code.

**Comment by finnaminope** [comment]
I accidentally deleted the branch on my repo.

**Comment by finnaminope** [comment]
Edit: I'm dumb

**Pull request closed without merging**
